- hosts: localhost
  become: true
  pre_tasks:
  - name: Update repositories
    apt: update_cache=yes
    changed_when: False

  tasks:
  - name: Install packages
    apt: name={{item}}
    with_items:
      - bridge-utils
      - curl
      - docker.io
      - gcc
      - libvirt-bin
      - maven
      - openjdk-8-jdk
      - python-dev
      - python-pip
      - python3-dev
      - python3-pip
      - qemu-kvm
      - terminator
      - ubuntu-vm-builder
      - vim
      - virt-manager
